### ISSUE TITLE
Negative torus does not contain center

### ISSUE THREAD

**Issue by hervasa2** [JuliaPhysics/SolidStateDetectors.jl#330]
Negative volumes do not include their surfaces as intended
However in the case of torus the "inner surface" at ``r_tube = 0`` get omitted because of this. 
 See example tube with torus removed bellow

<img width="106" alt="Screen Shot 2023-03-17 at 10 14 38 PM" src="https://user-images.githubusercontent.com/41748838/226082033-46d4b2fb-74c5-4f9e-aa83-cffa446542f2.png">

```
"torus": {
    "r_torus": 5.0,
    "r_tube": {
        "from": 0.0,
        "to": 2.0
    },
    "theta": {
        "from": "0.0°",
        "to": "360.0°"
    },
    "origin": [
        0.0,
        0.0,
        70.0
    ]
}
```

**Comment by fhagemann** [comment]
Thanks for reporting.
The problem is that for the `_in` method for `Torus`, we do not distinguish between [`FullTorus` and `HollowTorus`](https://github.com/JuliaPhysics/SolidStateDetectors.jl/blob/main/src/ConstructiveSolidGeometry/VolumePrimitives/Torus.jl#L124-L129). Therefore, even for a `FullTorus`, `r_tube_min = 0` is treated as a "real" boundary resulting in this unwanted behavior.
I will set up a PR to fix this now!

**Comment by fhagemann** [comment]
@hervasa2 Could you look through #331 ?
