### ISSUE TITLE
Improve IO regarding flexibility

### ISSUE THREAD

**Issue by lmh91** [JuliaPhysics/SolidStateDetectors.jl#68]

**Comment by fraseyboo** [comment]
Regarding this issue it might be useful to support writing VTK files using VTKWrite.jl, I currently use VTK for a lot of my PSA work because the wide support for large data types is unparalleled. All the fields and electrodes should be relatively simple to export as rectilinear grids and polydata and can be easily interpreted externally in Paraview, Visit, Slicer or a native VTK program. 

![ssd_potential_bottom](https://user-images.githubusercontent.com/33124758/111006264-664a5000-8384-11eb-8acb-eba16f756905.png)
![iso](https://user-images.githubusercontent.com/33124758/111006268-68acaa00-8384-11eb-809f-f273235238e6.png)

**Comment by oschulz** [comment]
Sounds very useful - we should add it as an optional dependency via Requires, though.
