### ISSUE TITLE
Radial charge density gradients in cartesian space

### ISSUE THREAD

**Issue by leenderthayen** [JuliaPhysics/SolidStateDetectors.jl#75]
Hi,

It seems like when specifying a radial charge distribution gradient in a cartesian grid, it takes the 'r' argument and turns it into an x gradient instead.

![radial_charge_density_error](https://user-images.githubusercontent.com/11664090/96788096-e1ed3580-13c0-11eb-8071-71fc79fac8ea.png)

**Comment by fhagemann** [comment]
Thanks for reporting, I will have a look at this today or tomorrow.

**Comment by lmh91** [comment]
I have been thinking about this. 

We, actually should add something like a `RadialChargeDensityModel`.
Or, better something like a `StandardCrystalChargeDensityModel` for pulled crystals. 
Because the name `RadialChargeDensityModel` would conflict with a gradient in `z`. 

And LinearChargeDensityModel should only take `x`,`y`,`z`.
